### ISSUE TITLE
Failure to install mu on Win XP and Xubuntu 14.04

### ISSUE THREAD

**Issue by nigelbennee** [eduvik/mu#15]
Having failed to either run the binaries of mu on my Acer with an exec error I downloaded the Windows variant onto my XP (SP3) desktop. After thinking about it for a bit it gives Fatal Error. run returns -1. The mbed serial driver is installed and working OK and the Microbit attaches its file system OK but no mu.
Running the Python online interface from the Microbit website works on both machines so the communications are OK on both, I am confused and my brain hurts.

**Comment by eduvik** [comment]
Hey; my fork doesn't have any binaries, and doesn't specifically target the microbit. You probably want to raise an issue at https://github.com/mu-editor/mu

**Comment by nigelbennee** [comment]
Thanks eduvik. I just followed links from microbit and obviously slipped off the rails. I will try again.
