### ISSUE TITLE
Can't find config.py

### ISSUE THREAD

**Issue by Tasm-Devil** [eduvik/mu#18]
See title.
I got it stating after manually installing these packages
python3-pyqt5
python3-pyqt5.qtserialport*
python3-pyqt5.qsci

but I don't know how to configure it. There is no config.py

Question 2: How do I use the setup.py?

Best regards and thanks for helping.
Pascal

**Comment by eduvik** [comment]
Which branch are you using? config.py first appeared in feature/multi-board (master doesn't depart massively from upstream). Switch to that branch, and its in mu/mu.

As for setup.py, I have no idea; I think that's for packaging up but nowhere near that stage.
