### ISSUE TITLE
talk over webREPL 

### ISSUE THREAD

**Issue by eduvik** [eduvik/mu#3]
the webREPL for supported devices would be nice to implement in mu. Bonus points for device auto-discovery, as well as first-time-connection simplification.

**Comment by askvictor** [comment]
Very preliminary success with webrepl: https://github.com/eduvik/mu/commit/cb3a5d1c23d687b1018eace3b957f3f3710397a1

**Comment by eduvik** [comment]
Working nicely in feature/multiboard
